### ISSUE TITLE
sunspot_rails gem bump?

### ISSUE THREAD

**Issue by jaredmoody** [sunspot/sunspot#1010]
It's been 8 months since c4e8af6557d0d3124e50cb05316ad57fbf5857e9 was merged which is required for compatibility with ruby 3 in rails - can we get a new release?

Would also close #1007

**Comment by rjschof** [comment]
It's a bit concerning that there has been zero effort by the maintainers of this gem to publish new releases since 2019. 

It might be time for the existing maintainers to appoint some new ones. As a last resort, we might consider forking this and publishing it as a new gem.

**Comment by cvoege** [comment]
@mlh758 @outoftime @alindeman @nz Tagging y'all since I can't tell who owns the repo/gem. Do one of you manage the gem and repo or do you know who does? If so could you tag them?

And for that person, are you still interested in maintaining this? If not, I'm guessing someone in the com.munity would be happy to take the reins. I would personally be happy to (though I'm not a master of the library yet)

**Comment by p8** [comment]
Tagging @serggl who created the last release.

**Comment by serggl** [comment]
Pushed `2.6.0` to rubygems

**Comment by p8** [comment]
Thanks @serggl ! 🥳 🙌

**Comment by rjschof** [comment]
> It's a bit concerning that there has been zero effort by the maintainers of this gem to publish new releases since 2019. 
> 
> 
> 
> It might be time for the existing maintainers to appoint some new ones. As a last resort, we might consider forking this and publishing it as a new gem.

This still rings true today. It's been 2 years.
