### ISSUE TITLE
Model#id is not accessible when indexing attributes

### ISSUE THREAD

**Issue by elado** [sunspot/sunspot#331]
When indexing attributes, in `searchable` block

```ruby
string(:test) { id }
```

raises an error

```
NoMethodError: undefined method `id' for #<Class:0x007fee2e4a09d8>
```

First impression from the code, is that `lib/sunspot/util.rb` defines:

```ruby
      def id
        @__calling_context__.__send__(:id)
      end
```

under `ContextBoundDelegate`

and the `@__calling_context__` points to the Model class and not the model instance.

I wasn't sure what that method was doing, and indexing works fine without it.
Also, it seems like no one is calling it while indexing or searching.

Is it essential?

**Comment by hagi** [comment]
@XsErG thanks for hint, works well

another solution without `@__receiver__`:
```ruby
string(:test) { my_id }

...

def my_id
  id
end
```

**Comment by cavi21** [comment]
Hi there bumping this in order to understand if there is a particular reason why `id` method is redefined within the `Utils` as @elado mention, seems that a PR changing that method to something around:
```ruby
      def id
        @__receiver__.__send__(:id)
      end
```
or maybe to prevent unexpected issues
```ruby
      def id
        begin
          @__calling_context__.__send__(:id)
        rescue ::NoMethodError => e
           begin
             @__receiver__.__send__(:id)
           rescue ::NoMethodError
             raise(e)
           end
         end
      end
```
Similar to the logic behind `method_missing(method, *args, &block)`

I didn't go through all the code so for sure I'm missing something, but it would be great if someone can put light on this topic in order to understand why `id` method is redefined the way it is.

Thanks!
