### ISSUE TITLE
Is it possible to get the term frequency?

### ISSUE THREAD

**Issue by tteng** [sunspot/sunspot#399]
Is it possible to get the term frequency and how to ? thx.

**Comment by jstdoit** [comment]
Is there any solutions?

**Comment by mlh758** [comment]
If you go to the solr dashboard, usually on port 8983 wherever you deployed solr, you can use the core selector to view the core you store this data on. There is information under the Schema tab about hit frequency. You can also run queries against the schema there.

Closing due to age here, will reopen if there are further questions.
