### ISSUE TITLE
A virtual field in `any` block?

### ISSUE THREAD

**Issue by novikserg** [sunspot/sunspot#779]
Hey there,

Thanks for an awesome gem! Our team loves it :)

I have a search like this:

``` ruby
Location.search do
  any do
    fulltext my_search_query
    fulltext fuzzy_query
  end
end
```

What I want to achieve here is to have a virtual attribute on every result from the second search (`fulltext fuzzy_query`), something like `fuzzy` which will return `true` on each results. Then I will be able to have all these result, and (in Ruby) pick ones with `fuzzy: true`, while having others without this field, so the goal is to have 1 single Solr request (to improve request time here and not do 2 consequent Solr request) and sort the results in Ruby.
I've checked all the docs but didn't find a solution. Is there a way I can do what I want? Am I doing it wrong way?

Thank you!

**Comment by bikeath1337** [comment]
@novikserg I know this is a late reply but...

When you do a fulltext search in SOLR, the scores are inherently fuzzy. I think that what you are trying to do is to search for "exact" matches vs "fuzzy" matches and then decide how to present the exact vs fuzzy matches.

The issue is that when you do a basic fulltext search, you're already creating fuzzy results through stemming, word delimiters, accent and case folding and character filters. Consider stemming: is a match on "goes" by searching for "go" exact or fuzzy?

The only way to get exact matches is to use a keyword search and not fulltext. However, if you want to still try this, then you'd probably have to create a searchable field that is a copy of what you'd search with exact, then analyze the hits scoring response to figure out which field matched which query clause.

It's all possible to a certain extent, but not very productive.
